"""
Module: interactive_points.migrations.0001_initial.py

This module represents a database 0001 migration for the interactive_points app
Creation of the Point module
"""
# Generated by Django 4.2.1 on 2023-06-04 11:37

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Represents a point model."""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(
                    srid=4326)),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='created_by_user',
                    to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='owned_by_user',
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
